// Using statements
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EntityFrameworkLecture.Models;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkLecture.Controllers;



public class PostController : Controller
{
    

    // _context is just a variable name, can be called anything (e.g. DATABASE, db, _db, etc)
    private EFLectureContext _context;

    private int? uid
    {
        get
        {
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    private bool loggedIn
    {
        get
        {
            return uid != null;
        }
    }
     
    // here we can "inject" our context service into the constructor
    public PostController(EFLectureContext context)
    {
        _context = context;
    }

    [HttpGet("/posts/all")]
    public IActionResult All()
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        List<Post> AllPosts = _context.Posts
        .Include(post => post.Author)
        // line below was to get author post count on post tile (BAD USE CASE)
        // .ThenInclude(author => author.CreatedPosts)
        .Include(post => post.Likes)
        .ToList();

        return View("All", AllPosts);
    }

    [HttpGet("/posts/new")]
    public IActionResult New()
    {
        int? userId = HttpContext.Session.GetInt32("UUID");
        if (userId == null)
        {
            return RedirectToAction("Index", "User");
        }

        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        return View("New");
    }

    [HttpPost("/posts/create")]
    public IActionResult Create(Post newPost)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        if (ModelState.IsValid == false) {
            // by not defaulting the return of View() in New, we can invoke the New() function & not have to re-write code
            // return View("New");

            return New();
        }

        if (uid != null)
        {
            newPost.UserId = (int)uid;
        }

        //this only runs if ModelState.IsValid == true
        _context.Posts.Add(newPost);
        // our sql database doesn't update until we save changes
        // after calling SaveChanges, our newPost will now have a value stored in PostId that was automatically generated by our database
        _context.SaveChanges();

        return RedirectToAction("All");
    }

    [HttpGet("/posts/{postId}")]
    public IActionResult ViewPost(int postId)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        // since firstordefault can return a single post, or null. our variable needs to be a nullable datatype
        Post? post = _context.Posts
            .Include(p => p.Author)
            .Include(p => p.Likes)
            // .ThenInclude is used for including something on the
            // object that was JUST included (for this example, our likes list)
            .ThenInclude(like => like.User)
            .FirstOrDefault(post => post.PostId == postId);
        
        // to get rid of "object might be null" warnings, write a conditional that checks for it & returns if it's null
        if (post == null)
        {
            return RedirectToAction("All");
        }
        
        return View("ViewPost", post);
    }

    [HttpPost("/posts/{deletedPostId}/delete")]
    public IActionResult Delete(int deletedPostId)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        Post? postToBeDeleted = _context.Posts.FirstOrDefault(post => post.PostId == deletedPostId);

        if (postToBeDeleted != null)
        {
            if(postToBeDeleted.UserId == uid)
            {
                _context.Posts.Remove(postToBeDeleted);
                _context.SaveChanges();
            }
        }

        return RedirectToAction("All");
    }

    [HttpGet("/posts/{postToBeEdited}/edit")]
    public IActionResult EditPost(int postToBeEdited)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        Post? post = _context.Posts.FirstOrDefault(post => post.PostId == postToBeEdited);

        if (post == null || post.UserId != uid)
        {
            return RedirectToAction("All");
        }

        return View("Edit", post);
    }

    [HttpPost("/posts/{updatedPostId}/update")]
    public IActionResult UpdatePost(int updatedPostId, Post updatedPost)
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        if (ModelState.IsValid == false)
        {
            // can remove all of the code below as long as we don't default our View() function in EditPost

            // Post? originalPost = _context.Posts.FirstOrDefault(post => post.PostId == updatedPost.PostId);
            // if (originalPost == null)
            // {
            //     RedirectToAction("All");
            // }
            // return View("Edit", originalPost);

            return EditPost(updatedPostId);
        }

        Post? dbPost = _context.Posts.FirstOrDefault(post => post.PostId == updatedPostId);

        if (dbPost == null || dbPost.UserId != uid)
        {
            return RedirectToAction("All");
        }

        dbPost.Topic = updatedPost.Topic;
        dbPost.Body = updatedPost.Body;
        dbPost.ImgUrl = updatedPost.ImgUrl;
        dbPost.UpdatedAt = DateTime.Now;

        _context.Posts.Update(dbPost);
        _context.SaveChanges();

        return RedirectToAction("ViewPost", new { postId = dbPost.PostId });
    }

    [HttpPost("/posts/{pId}/like")]
    public IActionResult Like(int pId)
    {
        if(!loggedIn || uid == null)
        {
            return RedirectToAction("Index", "User");
        }

        UserPostLike? existingLike = _context.UserPostLikes.FirstOrDefault(like => like.PostId == pId && like.UserId == uid);

        if (existingLike == null)
        {
            UserPostLike newLike = new UserPostLike(){
                PostId = pId,
                UserId = (int)uid
            };
            _context.UserPostLikes.Add(newLike);
        }
        else
        {
            _context.Remove(existingLike);
        }


        _context.SaveChanges();
        return RedirectToAction("All");
    }
 }

